services:
  - type: web
    name: movieminds-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: TMDB_API_KEY
        value: "your_tmdb_api_key_here"
