name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest
      - name: Lint with flake8
        run: flake8
      - name: Run tests
        run: pytest
      - name: Build Streamlit artifact
        run: |
          mkdir -p build
          cp app.py requirements.txt build/
          if [ -d model ]; then cp -r model build/; fi
          tar -czf streamlit_app.tar.gz -C build .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamlit-app
          path: streamlit_app.tar.gz
